# Generated by Django 2.2.1 on 2019-05-27 06:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('FILM', 'Film'), ('FOOD', 'Food'), ('TEAM', 'Team'), ('SPORT', 'Sport'), ('SONG', 'Song'), ('ALBUM', 'Album'), ('COUNTRY', 'Country'), ('CITY', 'City'), ('REGION', 'Region'), ('LANGUAGE', 'Language'), ('PERSON', 'Person')], default='FILM', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('creation_date', models.DateField(verbose_name='account created on')),
                ('last_pass_change', models.DateField(verbose_name='password last changed on')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FilePathField()),
                ('image_title', models.CharField(max_length=250)),
                ('creation_date', models.DateField(verbose_name='image created on')),
                ('categories', models.ManyToManyField(to='top_charts.Category')),
                ('tags', models.ManyToManyField(to='top_charts.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=250)),
                ('creation_date', models.DateField(verbose_name='chart created on')),
                ('modification_date', models.DateField(verbose_name='chart last modified on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_charts.User')),
            ],
        ),
    ]
