# Generated by Django 2.2.1 on 2019-06-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.FilePathField(max_length=4096),
        ),
    ]
