# Generated by Django 2.2.1 on 2019-06-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_charts', '0002_auto_20190602_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FilePathField(max_length=4096)),
                ('creation_date', models.DateField(verbose_name='image created on')),
                ('parent_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_charts.Image')),
            ],
        ),
    ]
